[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_macros = "0.1.1"
cute = "0.3.0"
once_cell = "1.18.0"
regex = "1.10.2"
termimad = "0.26.1"
